#!/bin/bash
export TINY_GRAPH="/home/scc11/lifeng/food/tiny"
export FLA_GRAPH="/home/scc11/lifeng/food/FLA-road"
export MESH_GRAPH="/home/scc11/lifeng/food/mesh.6pt"
export KKT_GRAPH="/home/scc11/lifeng/food/kkt_power"
export COPAPER_GRAPH="/home/scc11/lifeng/food/coPapers"
export AUDI_GRAPH="/home/scc11/lifeng/food/audikw1"
export RMAT1_GRAPH="/home/scc11/lifeng/food/rmat.5Mv.60Me"
export RMAT2_GRAPH="/home/scc11/lifeng/food/rmat.2Mv.100Me"
export AMAZON_GRAPH="/home/scc11/lifeng/food/Amazon"
export THERMAL_GRAPH="/home/scc11/lifeng/food/thermal2"
export LIVE_GRAPH="/home/scc11/lifeng/food/LiveJournal1"
export ECO_GRAPH="/home/scc11/lifeng/food/ecology1"
export RANDOM1_GRAPH="/home/scc11/lifeng/food/random.2Mv.128Me"
export RANDOM2_GRAPH="/home/scc11/lifeng/food/random.2Mv.100Me"