#!/bin/bash
export GRAPH_HOME="/home/chengyichao/food"
export TINY_GRAPH="${GRAPH_HOME}/tiny"
export FLA_GRAPH="${GRAPH_HOME}/FLA-road"
export MESH_GRAPH="${GRAPH_HOME}/mesh.6pt"
export KKT_GRAPH="${GRAPH_HOME}/kkt_power"
export COPAPER_GRAPH="${GRAPH_HOME}/coPapers"
export AUDI_GRAPH="${GRAPH_HOME}/audikw1"
export RMAT1_GRAPH="${GRAPH_HOME}/rmat.5Mv.60Me"
export RMAT2_GRAPH="${GRAPH_HOME}/rmat.2Mv.100Me"
export AMAZON_GRAPH="${GRAPH_HOME}/Amazon"
export THERMAL_GRAPH="${GRAPH_HOME}/thermal2"
export LIVE_GRAPH="${GRAPH_HOME}/LiveJournal1"
export ECO_GRAPH="${GRAPH_HOME}/ecology1"
export RANDOM1_GRAPH="${GRAPH_HOME}/random.2Mv.128Me"
export RANDOM2_GRAPH="${GRAPH_HOME}/random.2Mv.100Me"